# Use the existing mvictorn/yolo-backend image as the base image
FROM node

# Set the working directory inside the container (if necessary)
WORKDIR /app

# Copy any additional files or configurations your application needs
COPY backend/package*.json ./

# Install additional dependencies if required
RUN npm install

# Copy your application files
COPY backend/ /app/

# Expose port 5000 for the Node.js application (backend) - optional, if not already exposed in the base image
EXPOSE 5000

# Start the application with PM2 (or any other process manager you prefer) - optional, if not already started in the base image
CMD ["pm2-runtime", "server.js"]

