version: '3'
networks:
  yolo_ip2_network:
    external: true
    
services:
  # MongoDB Container
  mongo_db:
    container_name: mongo_ip2
    image: mongo:latest
    networks:
      - yolo_ip2_network
    volumes:
      - mongodb_data:/data/db

  # Node.js Backend Container with Ngrok
  backend:
    container_name: node_ip2
    build:
      context: .
      dockerfile: Dockerfile-node
    networks:
      - yolo_ip2_network
    depends_on:
      - mongo_db
    volumes:
      - ./app:/app
    ports:
      - "5000:5000"  # Map host port to container port
    # Start the application with PM2 (or any other process manager you prefer)
    command: ["npm", "start"]

  # Frontend Container (React Development Server)
  frontend:
    container_name: frontend_ip2
    build:
      context: .
      dockerfile: Dockerfile-frontend
    networks:
      - yolo_ip2_network
    ports:
      - "3000:3000"  # Map host port to container port
    # Start the React development server
    command: ["npm", "start"]

volumes:
  mongodb_data:
    driver: local

