apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: node:alpine
        ports:
        - containerPort: 3000
        resources:  
            limits:
              memory: "500Mi"
              cpu: "1Gi"
            requests:
              memory: "500Mi"
              cpu: "1Gi"
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30200
  type: LoadBalancer
