---
# tasks file for prepare-server
- name: Install Git
  apt:
    name: git
    state: present
    update_cache: yes

- name: Install Python 3
  apt:
    name: python3
    state: present
    update_cache: yes

- name: Install required dependencies for Docker
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg
    - software-properties-common
  tags: docker_dependencies

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Install Docker and Docker Compose
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose
    - nodejs
  notify: Restart Docker Service

# Define the handler
- name: Restart Docker Service
  service:
    name: docker
    state: restarted

- name: Ensure Docker service is started and enabled
  service:
    name: docker
    state: started
    enabled: yes

