---
- name: Build Node.js Backend Container
  docker_container:
    name: node_ip2
    image: node:alpine
    volumes:
      - node_data:/app
    ports:
      - "5000:5000"
    networks:
      - name: yolo_ip2_network
  become: yes

