---
- name: Pull image from repository
  docker_image:
    name: casperx7/ip2:node_ip2
    source: pull

- name: Create Node.js Backend Container
  docker_container:
    name: node_ip2
    image: casperx7/ip2:node_ip2
    networks:
      - name: yolo_ip2_network
    ports:
      - "5000:5000"
    command: "npm start"
  become: yes

